// todo not handeling void return!
time : ExternFn : extern fn() -> i64;
print_i64 : ExternFn : extern fn(int_to_print: i64) -> void;

fib : Fn : fn(fib_count: i64) -> i64 {
    // fibonacci
    a : i64 = 1;
    b : i64 = 0;

    i : i64 = 1;
    while (i < fib_count) {
        if (b > a) a += b;
        else b += a;

        i++;
    }

    if (a < b) return b;
    return a;
}

{
    time();
    i : i64 = 1;
    while (i < 92) {
        fib(i);
        i++;
    }
    print_i64(time());
} 
