// todo not handeling void return!
time : Fn : extern fn() -> i64;

{
    time();

    // fibonacci
    a : i64 = 1;
    b : i64 = 0;
    alternate : bool = false;

    // set to the desired n-th fibonacci number
    fib_count : i64 = 92;

    i : i64 = 1;
    while (i < fib_count) {
        if (alternate) a += b;
        else b += a;

        alternate = !alternate;
        i += 1;
    }

    time();

    if (a < b) return b;
    return a;
}