time : ExternFn : extern fn() -> i64;

inner : Fn : fn(fib_count: i64) -> i64 {
    // fibonacci
    a : i64 = 1;
    b : i64 = 0;
    alternate : bool = false;

    i : i64 = 1;
    while (i < fib_count) {
        if (alternate) a += b;
        else b += a;

        alternate = !alternate;
        i++;
    }

    if (a < b) return b;
    return a;
}

result : i64 = 0;


result = inner(92);



return result;